Repository kiali/openshift-servicemesh-plugin, pull requests merged in 2025-02, with the labels that each got.

#413 Copy kiali backports on tag creator GH action
  .github/workflows/tag-creator.yml
Labels: test: n/a

#416 Update elliptic dependency
  plugin/yarn.lock
Labels: maintenance, test: n/a

#414 Exclude waypoint tracing tests
  plugin/cypress.config.ts
  plugin/cypress/integration/openshift/common/sidebar_navigation.ts
  plugin/package.json
Labels: test: front-end/cypress

#419 Non blocking status call
  plugin/src/openshift/components/KialiController.tsx
Labels: enhancement

#418 Add CRD validation cypress tests
  plugin/cypress.config.ts
  plugin/cypress/integration/kiali/common/istio_config.ts
  plugin/cypress/integration/kiali/common/mesh.ts
  plugin/cypress/integration/kiali/common/workload_logs.ts
  plugin/cypress/integration/kiali/featureFiles/mesh.feature
  plugin/cypress/integration/kiali/featureFiles/service_details.feature
  plugin/cypress/integration/kiali/featureFiles/waypoint.feature
  plugin/cypress/integration/kiali/featureFiles/workload_logs.feature
  plugin/cypress/integration/openshift/common/istio_config.ts
  plugin/cypress/integration/openshift/common/istio_resources.ts
  plugin/cypress/integration/openshift/common/sidebar_navigation.ts
  plugin/cypress/integration/openshift/featureFiles/istio_config.feature
  plugin/cypress/support/commands.ts
  plugin/package.json
  plugin/src/kiali/README.md
  plugin/src/kiali/app/History.tsx
  plugin/src/kiali/components/Envoy/AccessLogModal.tsx
  plugin/src/kiali/components/Pf/PfBadges.tsx
  plugin/src/kiali/components/Pf/PfColors.tsx
  plugin/src/kiali/pages/Graph/GraphToolbar/GraphTraffic.tsx
  plugin/src/kiali/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  plugin/src/kiali/pages/WorkloadDetails/WorkloadPodLogs.tsx
  plugin/src/kiali/services/Api.ts
  plugin/src/kiali/types/IstioConfigList.ts
  plugin/src/kiali/types/IstioObjects.ts
Labels: test: front-end/cypress

#420 Update dompurify dependency
  plugin/package.json
  plugin/yarn.lock
Labels: test: n/a

#422 Update ubuntu version on GH actions
  .github/workflows/ci.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-creator.yml
  .yamlfmt
Labels: test: n/a
