Repository kiali/openshift-servicemesh-plugin, pull requests merged in 2025-06, with the labels that each got.

#452 Release PR title more concise
  .github/workflows/release.yaml
Labels: test: n/a

#454 [v2.11] backport: [CI] Specify parameters in cy.request (#453)
  plugin/cypress/integration/kiali/common/data/istio-shared-mesh-configmap.yaml
  plugin/cypress/integration/openshift/common/hooks.ts
Labels: bug

#458 [v2.4 Make OSSMC cypress tests agnostic to OCP version
  plugin/cypress/integration/openshift/common/istio_config.ts
  plugin/cypress/integration/openshift/common/sidebar_navigation.ts
  plugin/cypress/integration/openshift/common/table.ts
  plugin/cypress/support/commands.ts
Labels: test: front-end/cypress

#460 Update crypto-browserify and pbkdf2 dependencies
  plugin/yarn.lock
Labels: test: n/a, backport needed

#461 [v2.11] Update crypto-browserify and pbkdf2 dependencies (#460)
  plugin/yarn.lock
Labels: test: n/a
